# Generated by Django 5.1.3 on 2025-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delocation_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delocation',
            name='predict',
            field=models.BooleanField(default=False),
        ),
    ]
