# Generated by Django 5.1.3 on 2024-12-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_location_servo_angle_location_target_angle"),
    ]

    operations = [
        migrations.AddField(
            model_name="delocation",
            name="servo_angle",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="delocation",
            name="target_angle",
            field=models.FloatField(default=0),
        ),
    ]
