# Generated by Django 5.1.3 on 2025-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delocation_servo_angle_delocation_target_angle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
        migrations.AddField(
            model_name='delocation',
            name='predict',
            field=models.CharField(default='', max_length=100),
        ),
    ]
