# Generated by Django 5.1.3 on 2025-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_location_delocation_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delocation',
            name='predict',
            field=models.FloatField(default=0),
        ),
    ]
